# Generated by Django 6.0.1 on 2026-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20260125_1257'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique_recipetag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Разрешены символы латиницы, цифры, дефис и подчёркивание.', max_length=32, unique=True, verbose_name='Идентификатор тега'),
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
